### ISSUE TITLE
Support Prisjakt "Instore - avslutsuppföljning"

### ISSUE THREAD

**Issue by mattias-p** [pelmered/WooCommerce-Pricefiles#5]
I've got a customer who wants to know how much revenue Prisjakt generates for them. Prisjakt offers an extra-service called "Instore - avslutsuppföljning" that achieves this goal. However this extra-service requires that the URL:s in the pricefile contain the query parameter ref=prisjakt.

I suggest that this key value pair is added automatically to the Prisjakt pricefile. Since there is a tiny but non-zero risk that this collides with the URL:scheme you might also want an option to disable this feature.

I volunteer to implement this feature request, but before I start I'd like to hear your thoughts on the subject.

**Comment by pelmered** [comment]
I didn't know about this, but it seams like a good feature. It's also a feature that doesn't any complexity to speak of or any other drawbacks I can think of so I can't see a reason why not to add this. 

For the option add it to includes/admin/options.php with add_settings_field() like this: https://github.com/pelmered/WooCommerce-Pricefiles/blob/master/includes/admin/options.php#L260 (use the checkbox_option_callback callback) and then add a default value to the array here: https://github.com/pelmered/WooCommerce-Pricefiles/blob/master/includes/pricefiles.php#L347

**Comment by pelmered** [comment]
Oh, and use add_query_arg() ( http://codex.wordpress.org/Function_Reference/add_query_arg ) to ad the query parameter. That should make it quite safe to add the query param.
