### ISSUE TITLE
Add compatibility with network activated woocommerce

### ISSUE THREAD

**Issue by mikaelmattsson** [pelmered/WooCommerce-Pricefiles#8]
`if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) ` is not compatible with network activated plugins. Please use
`if ( is_plugin_active( 'woocommerce/woocommerce.php' ) ) `

**Comment by pelmered** [comment]
Thank you for reporting this issue. 

There is a big update comming up the next few weeks, and I will make this change. 
Have tried this change in the plugin on multisite? Did it work?

**Comment by pelmered** [comment]
Help wanted with testing in multisite/network install.

**Comment by mikaelmattsson** [comment]
Yes, I changed it and it works fine.

**Comment by pelmered** [comment]
Ok, thank you. That saves me some time. I will fix this in the next version.

**Comment by pelmered** [comment]
I added this now. This will be availlable in the next version on WordPress.org within a few weeks.
